use_frameworks!

platform :ios, '9.0'

target 'SDBaseClassLib_Example' do
  pod 'SDBaseClassLib', :path => '../'

  target 'SDBaseClassLib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
